export enum employmentType {
  FULL_TIME = 'Full Time',
  PART_TIME = 'Part Time',
  CONTRACT = 'contract',
  INTERN = 'Intern',
  FREELANCE = 'Freelance',
  TEMPORARY = 'Temporary',
  VOLUNTEER = 'Volunteer',
  APPRENTICESHIP = 'Apprenticeship',
  CO_OP = 'Co-op',
  SEASONAL = 'Seasonal',
  REMOTE = 'Remote',
  ONSITE = 'Onsite',
  HYBRID = 'Hybrid',
}
